// <auto-generated />
using System;
using HighLandCoffee.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HighLandCoffee.Migrations
{
    [DbContext(typeof(HighlandDB))]
    partial class HighlandDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("HighLandCoffee.Models.ChitietHD", b =>
                {
                    b.Property<int>("Machitiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Gia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mahd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mamon")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Soluongmua")
                        .HasColumnType("INTEGER");

                    b.HasKey("Machitiet");

                    b.HasIndex("Mahd");

                    b.HasIndex("Mamon");

                    b.ToTable("ChitietHD");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Dangnhap", b =>
                {
                    b.Property<string>("Tendn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Tendn");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Hoadon", b =>
                {
                    b.Property<int>("Mahd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Makh")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Ngaymua")
                        .HasColumnType("TEXT");

                    b.HasKey("Mahd");

                    b.HasIndex("Makh");

                    b.ToTable("Hoadon");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Khachhang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenkh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Makh");

                    b.ToTable("Khachhang");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Loai", b =>
                {
                    b.Property<string>("Maloai")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Maloai");

                    b.ToTable("Loai");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Monan", b =>
                {
                    b.Property<int>("Mamon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Anh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Gia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Maloai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Soluong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tenmon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Mamon");

                    b.HasIndex("Maloai");

                    b.ToTable("Monan");
                });

            modelBuilder.Entity("HighLandCoffee.Models.ChitietHD", b =>
                {
                    b.HasOne("HighLandCoffee.Models.Hoadon", "Hoadon")
                        .WithMany()
                        .HasForeignKey("Mahd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HighLandCoffee.Models.Monan", "Monan")
                        .WithMany()
                        .HasForeignKey("Mamon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoadon");

                    b.Navigation("Monan");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Hoadon", b =>
                {
                    b.HasOne("HighLandCoffee.Models.Khachhang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("Makh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");
                });

            modelBuilder.Entity("HighLandCoffee.Models.Monan", b =>
                {
                    b.HasOne("HighLandCoffee.Models.Loai", "Loai")
                        .WithMany()
                        .HasForeignKey("Maloai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loai");
                });
#pragma warning restore 612, 618
        }
    }
}
